---
title: "Graphs"
author: "Alex Rhomberg"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggformula)
library(png)
library(ggpubr)
library(grid)
load("SavedData.rda")
```

## R Markdown

```{r}
img <- png::readPNG("soccerfield.png")
```


```{r Long Ball}

#longBallClean %>% gf_bin2d(longbally ~ longballx, color =~ LongBallSuccess, binwidth = c(1,1)) + scale_fill_continuous(guide = FALSE) + annotation_custom(rasterGrob(img, width = unit(0.82, "npc"),height = unit(1.1,"npc")),-Inf, Inf, -Inf, Inf) #+ lims(x=c(-0.5,4.5), y = c(0,6))

longBallClean %>% gf_point(longbally ~ longballx, color =~ LongBallSuccess, width = 1, height = 1) + scale_fill_continuous(guide = FALSE) + annotation_custom(rasterGrob(img, width = unit(0.82, "npc"),height = unit(1.1,"npc")),-Inf, Inf, -Inf, Inf) + lims(x=c(-0.6,4.6), y = c(0,6))

longBallClean %>% filter(LongBallSuccess == 1) %>% gf_point(longbally ~ longballx, width = 1, height = 1) + scale_fill_continuous(guide = FALSE) + annotation_custom(rasterGrob(img, width = unit(0.82, "npc"),height = unit(1.1,"npc")),-Inf, Inf, -Inf, Inf) + lims(x=c(-0.6,4.6), y = c(0,6))

```

```{r Long Ball Game Duration}
longBallClean %>% filter(LongBallTimeStamp <= 95) %>% gf_point(LongBall~LongBallTimeStamp, color =~ LongBallSuccess)
```


```{r Long Ball Success Rates}
longBallClean %>%  group_by(LongBallSuccess) %>% 
  count() %>% spread(LongBallSuccess, n) %>% mutate(Tries = `1`+`2`,
    SuccessRate = `1`/Tries) %>% rename(Successes = `1`, Fails = `2`) 
```


```{r Long Ball Successs Rate by Player}
longBallClean %>%  group_by(LongBall, LongBallSuccess) %>% 
  count() %>% spread(LongBallSuccess, n) %>% 
  mutate( `1` = replace_na(`1`,0),
          `2` = replace_na(`2`,0)) %>%
  mutate(Tries = `1`+`2`,
    SuccessRate = `1`/Tries ) %>%
  rename(JerseyNumber = LongBall,
         Successes = `1`,
         Fails = `2`) %>%
  arrange(desc(Successes, SuccessRate))  
```


```{r Key Pass}
keyPassClean %>% gf_point(keyPassy ~ keyPassx,width = 1, height = 1) + scale_fill_continuous(guide = FALSE) + annotation_custom(rasterGrob(img, width = unit(0.82, "npc"),height = unit(1.1,"npc")),-Inf, Inf, -Inf, Inf) + lims(x=c(-0.6,4.6), y = c(0,5))
```

```{r Key Pass Game Duration}
keyPassClean %>% filter(KeyPassTimeStamp <= 95) %>% gf_point(KeyPass~KeyPassTimeStamp) 
```


```{r Key Pass by Player}
keyPassClean %>%  group_by(KeyPass) %>% 
  count() %>% rename(JerseyNumber = KeyPass, numberOfKeyPasses = n) %>% arrange(desc(numberOfKeyPasses))
```

```{r Take On}
takeOnClean %>% gf_point(takeOny ~ takeOnx, width = 1, height = 1) + scale_fill_continuous(guide = FALSE) + annotation_custom(rasterGrob(img, width = unit(0.82, "npc"),height = unit(1.1,"npc")),-Inf, Inf, -Inf, Inf) + lims(x=c(-0.6,4.6), y = c(0,5))
```

```{r Take On Game Duration}
takeOnClean %>% filter(TakeOnTimeStamp <= 95) %>% gf_point(TakeOn~TakeOnTimeStamp)
```

```{r Take On Successs Rate by Player}
takeOnClean %>%  group_by(TakeOn, TakeOnSuccess) %>% 
  count() %>% spread(TakeOnSuccess, n) %>% 
  mutate( `1` = replace_na(`1`,0),
          `2` = replace_na(`2`,0)) %>%
  mutate(Tries = `1`+`2`,
    SuccessRate = `1`/Tries ) %>%
  rename(JerseyNumber = TakeOn,
         Successes = `1`,
         Fails = `2`) %>%
  arrange(desc(Successes, SuccessRate))  
```

```{r Goal Game Duration}
goalRaw %>% filter(GoalTimeStamp <= 95) %>% gf_point(Goal~GoalTimeStamp)
```

```{r GoalHow table}
goalRaw %>% group_by(GoalHow) %>% count() %>% spread(GoalHow, n)
```

```{r GoalWhere table}
goalRaw %>% group_by(GoalWhere) %>% count() %>% spread(GoalWhere, n)
```

```{r GoalWhich table}
goalRaw %>% group_by(GoalWhich) %>% count() %>% arrange(desc(n))
```


```{r Assist Game Duration}
assistClean %>% filter(AssistTimeStamp <= 95) %>% gf_point(Assist~AssistTimeStamp)
```

```{r Shot Game Duration}
shotRaw %>% filter(ShotTimeStamp <= 95) %>% gf_point(Shot~ShotTimeStamp, color =~ ShotFrame)
```

```{r Steal How by Player}
stealClean %>%  group_by(Steal, StealHow) %>% 
  count() %>% spread(StealHow, n) %>% 
  mutate( `1` = replace_na(`1`,0),
          `2` = replace_na(`2`,0)) %>% mutate(Total = `1` + `2`) %>%
  rename(JerseyNumber = Steal,
      Foot = `1`,
         Head = `2`) %>%
  arrange(desc(Total)) 
```



```{r Steal Game Duration}
stealClean %>% filter(StealTimeStamp <= 95) %>% gf_point(Steal~StealTimeStamp)
```

```{r Tackle How by Player}
tackleClean %>%  group_by(Tackle, TackleHow) %>% 
  count() %>% spread(TackleHow, n) %>% 
  mutate( `1` = replace_na(`1`,0),
          `2` = replace_na(`2`,0)) %>% mutate(Total = `1` + `2`) %>%
  rename(JerseyNumber = Tackle,
      Standing = `1`,
         Sliding = `2`) %>%
  arrange(desc(Total)) 
```

```{r Tackle Game Duration}
tackleClean %>% filter(TackleTimeStamp <= 95) %>% gf_point(Tackle~TackleTimeStamp)
```

```{r Turnover}
turnoverClean %>% gf_point(turnovery ~ turnoverx, width = 1, height = 1) + scale_fill_continuous(guide = FALSE) + annotation_custom(rasterGrob(img, width = unit(0.82, "npc"),height = unit(1.1,"npc")),-Inf, Inf, -Inf, Inf) + lims(x=c(-0.6,4.6), y = c(0,5))
```

```{r Turnover Game Duration}
turnoverClean %>% filter(TurnoverTimeStamp <= 95) %>% gf_point(Turnover~TurnoverTimeStamp)
```

```{r Turnover How by Player}
turnoverClean %>%  group_by(Turnover, TurnoverHow) %>% 
  count() %>% spread(TurnoverHow, n) %>% 
  mutate( `1` = replace_na(`1`,0),
          `2` = replace_na(`2`,0)) %>% mutate(Total = `1` + `2`) %>%
  rename(JerseyNumber = Turnover,
      Pass = `1`,
         Standing = `2`) %>%
  arrange(desc(Total)) 
```

```{r Pressure}
pressureClean %>% gf_point(pressurey ~ pressurex, color =~ PressureSuccess, width = 1, height = 1) + scale_fill_continuous(guide = FALSE) + annotation_custom(rasterGrob(img, width = unit(0.82, "npc"),height = unit(1.1,"npc")),-Inf, Inf, -Inf, Inf) + lims(x=c(-0.6,4.6), y = c(0,5))
```

```{r Presssure Game Duration}
pressureClean %>% filter(PressureTimeStamp <= 95) %>% gf_point(Pressure~PressureTimeStamp)
```

```{r Pressure Success Rates}
pressureClean %>%  group_by(PressureSuccess) %>% 
  count() %>% spread(PressureSuccess, n) %>% mutate(Tries = `1`+`2`,
    SuccessRate = `1`/Tries) %>% rename(Successes = `1`, Fails = `2`) 
```

```{r Pressure Successs Rate by Player}
pressureClean %>%  group_by(Pressure, PressureSuccess) %>% 
  count() %>% spread(PressureSuccess, n) %>% 
  mutate( `1` = replace_na(`1`,0),
          `2` = replace_na(`2`,0)) %>%
  mutate(Tries = `1`+`2`,
    SuccessRate = `1`/Tries ) %>%
  rename(JerseyNumber = Pressure,
         Successes = `1`,
         Fails = `2`) %>%
  arrange(desc(Successes, SuccessRate))  
```

```{r Allowed Shot Game Duration}
allowedShotRaw %>% filter(AllowedShotTimeStamp <= 95) %>% gf_point(AllowedShot~AllowedShotTimeStamp)
```
